### ISSUE TITLE
Get travis ci passing

### ISSUE THREAD

**Issue by Praesidiarius** [OnePlc/PLC_X_Core#4]
lets have a build passing, fix issues which are mostly setup related

**Comment by Praesidiarius** [comment]
i really need some help with this error if anyone has an idea

Laminas\ServiceManager\Exception\ServiceNotCreatedException: Service with name "Application\Controller\IndexController" could not be created. Reason: Connect Error: SQLSTATE[HY000] [2002] No such file or directory

docker-compose.yml 
```
oneplc:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8080:80"
  volumes:
   - .:/var/www
localhost:
  image: mariadb
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: plcdemo
```

Dockerfile
```
FROM php:7.3-apache

RUN apt-get update \
 && apt-get install -y git zlib1g-dev libicu-dev libzip-dev\
 && docker-php-ext-install zip \
 && docker-php-ext-install pdo pdo_mysql \
 && docker-php-ext-install intl \
 && a2enmod rewrite \
 && sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/sites-available/000-default.conf \
 && mv /var/www/html /var/www/public \
 && curl -sS https://getcomposer.org/installer \
  | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www
```
